import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + " h-screen"}>
                <Header />
                <main className="flex container mx-auto p-1 pb-0 pt-0">{children}</main>
                <footer className="footer-height bg-gray-200 p-1 text-center">
                    <p>&copy; {new Date().getFullYear()} Nutritionist Lab Helper. All rights reserved.</p>
                </footer>
            </body>
        </html>
    );
}
